---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: podinfo
  namespace: backstage
  labels:
    app.kubernetes.io/component: carts-service
    backstage.io/kubernetes-id: carts-service
spec:
  image: stefanprodan/podinfo
  interval: 1h
  provider: generic
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: podinfo
  namespace: backstage
  labels:
    app.kubernetes.io/component: carts-service
    backstage.io/kubernetes-id: carts-service
spec:
  imageRepositoryRef:
    name: podinfo
  policy:
    semver:
      range: 5.1.x
