---
# NOTE: This is deliberately designed to always fail (exit code 1)
# This makes it show up in the Kubernetes plugin as a crashing pod.
apiVersion: batch/v1
kind: CronJob
metadata:
  name: payments-service-cronjob
  namespace: backstage
  labels:
    app.kubernetes.io/component: payments-service
    backstage.io/kubernetes-id: payments-service
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/component: payments-service
            backstage.io/kubernetes-id: payments-service
        spec:
          containers:
          - name: cleanup
            image: busybox:latest
            imagePullPolicy: IfNotPresent
            # This will always fail 
            command:
            - /bin/sh
            - -c
            - "echo 'This is just a failing CronJob' && exit 1"
          restartPolicy: OnFailure
