---
apiVersion: v1
kind: Secret
metadata:
  name: backstage-service-account-creds
  namespace: backstage
  annotations:
    kubernetes.io/service-account.name: backstage
type: kubernetes.io/service-account-token
