---
apiVersion: v1
kind: Namespace
metadata:
  name: shipping-service
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: shipping-service-podinfo
  namespace: backstage
  labels:
    backstage.io/kubernetes-id: shipping-service
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: shipping-service-podinfo
    namespace: backstage
  path: "./kustomize"
  prune: true
  timeout: 1m
  targetNamespace: shipping-service
  commonMetadata:
    labels:
      backstage.io/kubernetes-id: shipping-service
