apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sync-flux-resources
rules:
  - apiGroups: ['source.toolkit.fluxcd.io']
    resources:
      [
        'buckets',
        'helmcharts',
        'gitrepositories',
        'helmrepositories',
        'ocirepositories',
      ]
    verbs: ['patch']
  - apiGroups: ['kustomize.toolkit.fluxcd.io']
    resources: ['kustomizations']
    verbs: ['patch']
  - apiGroups: ['helm.toolkit.fluxcd.io']
    resources: ['helmreleases']
    verbs: ['patch']
