---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: backstage
  namespace: backstage
spec:
  interval: 5m
  chart:
    spec:
      chart: backstage
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: backstage-charts
        namespace: backstage
      interval: 60m
  values:
    # See the chart documentation for the values below
    backstage:
      image:
        registry: # insert the registry e.g. ghcr.io
        repository: # path to the repository
        tag: # to be used
      # extraAppConfig:
      #   - filename: app-config.local.yaml
      #     configMapRef: backstage-app-config
      extraEnvVarsSecrets:
        - backstage-oauth-secret
    # Note you will need to apply the RBAC in this repository to allow the SA to
    # access resources.
    serviceAccount:
      name: backstage
